# Generated by Django 5.0.3 on 2024-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(blank=True, upload_to='media/site/')),
                ('caption1', models.TextField(blank=True)),
                ('banner2', models.ImageField(blank=True, upload_to='media/site/')),
                ('caption2', models.TextField(blank=True)),
                ('banner3', models.ImageField(blank=True, upload_to='media/site/')),
                ('caption3', models.TextField(blank=True)),
                ('special_offer_banner', models.ImageField(blank=True, null=True, upload_to='media/site/special_offers/')),
                ('special_offer_caption', models.TextField(blank=True)),
            ],
        ),
    ]
