# Generated by Django 5.0.3 on 2024-04-08 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='subcategory_images/'),
            preserve_default=False,
        ),
    ]
