# Generated by Django 5.0.3 on 2024-04-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_colors_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, to='Products.discount'),
        ),
    ]
